# Terraform / Ansible integration.
#
# A single null_resource provisioner writes an inventory describing the Linux
# nodes that were just built, then runs the project playbook against them. This
# is what makes `terraform apply --auto-approve` configure the guest operating
# systems as well as create the infrastructure, with no interactive step.
#
# It stays a single null_resource so `terraform state list` remains at 48.

locals {
  # Deterministic ordering so vm1.html always lands on the same node.
  vm_list = sort(tolist(var.vm_names))

  # One inventory line per node, carrying the Azure FQDN as a host variable so
  # the webserver role can publish it.
  inventory_hosts = join("\n", [
    for k in local.vm_list :
    format(
      "%s ansible_host=%s node_fqdn=%s",
      azurerm_linux_virtual_machine.linux_vm[k].computer_name,
      azurerm_public_ip.linux_pip[k].ip_address,
      azurerm_public_ip.linux_pip[k].fqdn
    )
  ])

  inventory_content = <<-INV
    # Generated by Terraform - do not edit by hand.
    [linux]
    ${local.inventory_hosts}

    [linux:vars]
    ansible_user=${var.admin_username}
    ansible_ssh_private_key_file=${var.ssh_private_key_path}
    ansible_python_interpreter=/usr/bin/python3
  INV
}

resource "null_resource" "ansible_provision" {
  # Re-run whenever any VM is replaced.
  triggers = {
    vm_ids = join(",", [for k in local.vm_list : azurerm_linux_virtual_machine.linux_vm[k].id])
  }

  # Wait until SSH is actually answering on every node before handing over to
  # Ansible, otherwise the first play can race the boot.
  provisioner "remote-exec" {
    connection {
      type        = "ssh"
      host        = azurerm_public_ip.linux_pip[local.vm_list[0]].ip_address
      user        = var.admin_username
      private_key = file(pathexpand(var.ssh_private_key_path))
      timeout     = "5m"
    }
    inline = ["echo 'VM1 reachable, starting Ansible'"]
  }

  provisioner "remote-exec" {
    connection {
      type        = "ssh"
      host        = azurerm_public_ip.linux_pip[local.vm_list[1]].ip_address
      user        = var.admin_username
      private_key = file(pathexpand(var.ssh_private_key_path))
      timeout     = "5m"
    }
    inline = ["echo 'VM2 reachable'"]
  }

  provisioner "remote-exec" {
    connection {
      type        = "ssh"
      host        = azurerm_public_ip.linux_pip[local.vm_list[2]].ip_address
      user        = var.admin_username
      private_key = file(pathexpand(var.ssh_private_key_path))
      timeout     = "5m"
    }
    inline = ["echo 'VM3 reachable'"]
  }

  # Write the inventory next to the playbook.
  provisioner "local-exec" {
    working_dir = var.ansible_dir
    command     = "cat > inventory.ini <<'TFINV'\n${local.inventory_content}\nTFINV"
    interpreter = ["/bin/bash", "-c"]
  }

  # Run the playbook. ANSIBLE_CONFIG makes sure the role paths resolve no
  # matter which directory terraform was invoked from.
  provisioner "local-exec" {
    working_dir = var.ansible_dir
    command     = "ansible-playbook ${var.ansible_playbook}"
    interpreter = ["/bin/bash", "-c"]

    environment = {
      ANSIBLE_CONFIG            = "ansible.cfg"
      ANSIBLE_HOST_KEY_CHECKING = "False"
      ANSIBLE_FORCE_COLOR       = "1"
    }
  }

  depends_on = [
    azurerm_virtual_machine_extension.netwatcher,
    azurerm_virtual_machine_extension.monitor,
  ]
}
